"""
Ligand embeddings were generated by combining
15 physicochemical descriptors and a 1024-bit
Morgan fingerprint (ECFP4), resulting in a
1039-dimensional ligand feature vector.
"""

import pandas as pd
import numpy as np
import csv
import os
import torch
import torch.nn as nn

import matplotlib.pyplot as plt
from tqdm import tqdm

from rdkit import Chem, DataStructs
from rdkit.Chem import AllChem, Descriptors, rdMolDescriptors, Crippen
from rdkit.ML.Descriptors import MoleculeDescriptors

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_samples, silhouette_score
from sklearn.preprocessing import StandardScaler

from Bio.PDB import PDBParser
from Bio.PDB import NeighborSearch

ligands_file = "Database/drugbank/approved_drugs.sdf"

# ligands information

supplier = Chem.SDMolSupplier(ligands_file)
mol_count = sum(1 for mol in supplier if mol is not None)

print(f"Total {mol_count} ligands")

# rdkit descriptor list
descriptor_names = [name for name, _ in Descriptors.descList]
print('\n'.join(descriptor_names))


### Embedding ###

ACIDIC_SMARTS = [
    Chem.MolFromSmarts('[CX3](=O)[OX1H0-,OX2H1]'),
    Chem.MolFromSmarts('S(=O)(=O)[OH]'),
    Chem.MolFromSmarts('P(=O)(O)(O)O'),
    Chem.MolFromSmarts('c[OH]')
]
BASIC_SMARTS = [
    Chem.MolFromSmarts('[NX3;H2,H1,H0;!$(NC=O)]'),
    Chem.MolFromSmarts('n1cccc1'),
    Chem.MolFromSmarts('C(=N)N'),
    Chem.MolFromSmarts('N-C(=N)-N')
]
FEATURE_KEYS = [
    'HBD','HBA','RotBonds','AromRings',
    'Heteroatoms','TPSA','Csp3','FormalCharge',
    'MolWt','LabuteASA','LogP','DonorAcceptorRatio',
    'AcidicEstimate','BasicEstimate','HydrophobicEstimate'
]

def count_groups(mol, smarts_list):
    cnt = 0
    for patt in smarts_list:
        if patt is None: continue
        cnt += len(mol.GetSubstructMatches(patt))
    return cnt

def hydrophobicity_vsa(mol):
    bins = [
        Descriptors.SlogP_VSA1(mol), Descriptors.SlogP_VSA2(mol), Descriptors.SlogP_VSA3(mol),
        Descriptors.SlogP_VSA4(mol), Descriptors.SlogP_VSA5(mol), Descriptors.SlogP_VSA6(mol),
        Descriptors.SlogP_VSA7(mol), Descriptors.SlogP_VSA8(mol), Descriptors.SlogP_VSA9(mol),
        Descriptors.SlogP_VSA10(mol),
    ]
    return sum(bins[0:3]), sum(bins[6:10])

def compute_features_15d(mol):
    HBD = Descriptors.NumHDonors(mol)
    HBA = Descriptors.NumHAcceptors(mol)
    RotBonds = Descriptors.NumRotatableBonds(mol)
    AromRings = Descriptors.NumAromaticRings(mol)
    try:
        Heteroatoms = Descriptors.NumHeteroatoms(mol)
    except Exception:
        Heteroatoms = rdmd.CalcNumHeteroatoms(mol)
    TPSA = Descriptors.TPSA(mol)
    Csp3 = Descriptors.FractionCSP3(mol)
    FormalCharge = sum(a.GetFormalCharge() for a in mol.GetAtoms())
    MolWt = Descriptors.MolWt(mol)
    LabuteASA = Descriptors.LabuteASA(mol)
    LogP = Crippen.MolLogP(mol)
    DonorAcceptorRatio = float(HBD) / (float(HBA) + 1e-5)

    acidic_cnt = count_groups(mol, ACIDIC_SMARTS)
    basic_cnt  = count_groups(mol, BASIC_SMARTS)
    hydrophilic_vsa, hydrophobic_vsa = hydrophobicity_vsa(mol)

    AcidicEstimate      = TPSA + acidic_cnt + hydrophilic_vsa
    BasicEstimate       = max(FormalCharge, 0.0) + basic_cnt
    HydrophobicEstimate = LogP + Csp3 + AromRings + hydrophobic_vsa

    feats = {
        'HBD':HBD,'HBA':HBA,'RotBonds':RotBonds,'AromRings':AromRings,
        'Heteroatoms':Heteroatoms,'TPSA':TPSA,'Csp3':Csp3,'FormalCharge':FormalCharge,
        'MolWt':MolWt,'LabuteASA':LabuteASA,'LogP':LogP,'DonorAcceptorRatio':DonorAcceptorRatio,
        'AcidicEstimate':AcidicEstimate,'BasicEstimate':BasicEstimate,'HydrophobicEstimate':HydrophobicEstimate
    }
    v15 = torch.tensor([feats[k] for k in FEATURE_KEYS], dtype=torch.float32)  
    return v15

def ecfp1024(mol, radius=2, nBits=1024, useChirality=True):
    fp = AllChem.GetMorganFingerprintAsBitVect(mol, radius=radius, nBits=nBits, useChirality=useChirality)
    arr = np.zeros((nBits,), dtype=np.int8)
    DataStructs.ConvertToNumpyArray(fp, arr)
    return torch.from_numpy(arr.astype(np.float32))

def compute_ligand_vec_1039(mol):
    try:
        v15 = compute_features_15d(mol)               
        vfp = ecfp1024(mol, radius=2, nBits=1024)     
        v   = torch.cat([v15, vfp], dim=0)            
        if torch.isnan(v).any() or torch.isinf(v).any():
            return None
        return v
    except Exception as e:
        print(f"Fail: {e}")
        return None

def process_drugbank_sdf_with_names(sdf_file):
    suppl = Chem.SDMolSupplier(sdf_file, sanitize=True, removeHs=False)
    vecs, names = [], []
    ok = fail = 0

    for mol in tqdm(suppl, desc="DrugBank ligands (15D+ECFP1024)"):
        if mol is None:
            fail += 1; continue

        v = compute_ligand_vec_1039(mol)
        if v is None:
            fail += 1; continue
        vecs.append(v); ok += 1

        if mol.HasProp("DRUGBANK_ID"):
            dbid = mol.GetProp("DRUGBANK_ID")
        elif mol.HasProp("DRUGBANK_ACCESSION"):
            dbid = mol.GetProp("DRUGBANK_ACCESSION")
        else:
            dbid = "UNKNOWN_ID"
        gname = mol.GetProp("GENERIC_NAME") if mol.HasProp("GENERIC_NAME") else ""
        label = f"{dbid} ({gname})" if gname else dbid
        names.append(label)

    if not vecs:
        raise RuntimeError("All molecules fail")
    X = torch.stack(vecs, dim=0) 
    print(f"Success: {ok} / Fail: {fail} | X.shape={X.shape}")
    return X, names


X_L, ligand_names = process_drugbank_sdf_with_names(ligands_file)
torch.save({"X_L": X_L, "names": ligand_names}, "path/to/save/model.pt")
